BTCGPU/BTCGPU

- contrib/debian/bitcoin-qt.desktop
Change the description in bitcoin-qt.desktop
> Change the description in bitcoin-qt.desktop

- configure.ac
- contrib/init/bitcoind.openrc
Rename and rewrite description.
> Change the name from "bitcoin" to "bgold"

- README.md
Because inquiring minds are planning on their BTC carving
> Be more specific about the fork date

- src/qt/guiconstants.h
Added our site url, now that our site is finished.
> Link to our website.

- contrib/qos/README.md
- contrib/qos/tc.sh
- doc/developer-notes.md
- doc/man/bitcoin-qt.1
- doc/man/bitcoind.1
- doc/tor.md
- src/rpc/net.cpp
Still more places, but this is a good start.
> Fix port number in various docs and other places

- doc/build-osx.md
Updated build tutorial for OSX contributors  (missing dependencies) .
> updated for OSX builders

- src/chainparams.cpp
- Use the same network magic for testnet.
> Minor fixes

- src/chainparams.cpp
- src/pow.cpp
For reference.
https://github.com/BTCGPU/BTCGPU/issues/78
> Adjusted difficulty change based on issue #78

- src/net.cpp
- src/validation.cpp
- Allow bitcoin magic whe bootstraping
- Temporarily disable premine conbase check
> Minor fixes.

- contrib/linearize/example-linearize.cfg
- contrib/linearize/linearize-data.py
It's needed to produce `bootstrap.dat` file for Bitcoin Gold.
Tested:
manually create a bootstrap file for 500061 blocks.
> Fix linearize-data.py for BTG block format.

- contrib/gitian-descriptors/gitian-linux.yml
- contrib/gitian-descriptors/gitian-osx.yml
- contrib/gitian-descriptors/gitian-win.yml
Here you go fresh and clean :)
> Fixed gitian build

- src/qt/guiconstants.h
URL updated for the main website.
> Updated website url.

- src/crypto/equihash.cpp
- src/crypto/equihash.h
- src/crypto/equihash.tcc
- src/leveldb/util/logging.cc
- src/txdb.cpp
Integrated fixed from another PR and added more fixes
fixes #47
> Fix integer comparison warnings for equihash.cpp/h

- .github/ISSUE_TEMPLATE.md
- src/chainparams.cpp
- src/validation.cpp
> Fix the bad conditions to skip premine whitelist for regtest mode.

- src/chainparams.cpp
- src/chainparams.h
- src/consensus/params.h
- src/init.cpp
- src/net.cpp
- src/net.h
- src/net_processing.cpp
- src/netbase.cpp
- src/netbase.h
- src/rpc/net.cpp
- src/validation.cpp
- test/functional/test_framework/mininode.py
- Completely removed `-bootstrap`.
- New testnet magic.
- Fixed bad serialization code in functional test mininode.
Tested:
Download the blockchain from scratch.
> Remove `-bootstrap` and minor fixes

- configure.ac
> Add check to libsodium version in configure.ac

- contrib/gitian-build.sh
- added missing quotes to signProg 
- introduced the ability to pass own gitian.sig and bitcoingold-detached-sigs repo urls
> Missing quotes and new parameters

- src/rpc/server.cpp
Simple change the name on help function
> name of client changed

- src/bitcoin-cli.cpp
- src/bitcoind.cpp
- src/chainparamsbase.h
- src/clientversion.cpp
- src/init.cpp
- src/interfaces/node.h
- src/noui.cpp
- src/rpc/protocol.h
- src/rpc/rawtransaction.cpp
- src/test/README.md
- src/util.cpp
- src/wallet/rpcdump.cpp
- src/wallet/rpcwallet.cpp
- src/wallet/test/wallet_tests.cpp
As a remaining of bitcoin core, the code contains reference to bitcoind. This PR rename it as bgoldd.
> Refactor: server name changes

- src/crypto/equihash.h
> Add include stdexcept to equihash.h

- src/chainparams.cpp
This problem was introduced by auto-merge.
> Fix wrong dnsseed initialization parameter

- src/qt/transactionview.cpp
As reported by Fabian Braeunlein of PS Positive Security GmbH
> [qt] only allow https explorer links

- README.md
Domain switch
Correcting URLs, language, typo.
> Update README.md for new domain
